language: node_js
node_js:
- "10"
- "12"
- "14"

install:
  - npm install

script:
  - npm run lint
  - npm run coverage
  - npm run build

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
